baseURL = "https://emakryo.github.io"
languageCode = "ja-jp"
title = "emakryo's blog"
theme = "ananke"

hasCJKLanguage = true
googleAnalytics = "G-8K4KNS60G7"

[params]
github = "https://github.com/emakryo/emakryo.github.io"
twitter = "https://twitter.com/cruelturtle"
linkedin = "https://www.linkedin.com/in/諒亮-亀澤-8503a1176/?locale=en_US"
