# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ source ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Initialize submodules
      run: git submodule update --init --recursive
    
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.9
    
    - name: Build sites
      run: hugo
      
    - name: Publish
      run: |
        git checkout master
        ls
        ls | grep -v public | xargs rm -r
        mv public/* .
        git add .
        git status
        echo "Auto commit by Github actions $GITHUB_RUN_ID"
